[project]
name = "gradio-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.20.0",
    "matplotlib>=3.10.1",
    "openai>=1.65.3",
    "python-dotenv>=1.0.1",
    "streamlit>=1.43.0",
]
