[project]
name = "opencv-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.20.0",
    "opencv-python>=4.11.0.86",
    "spaces>=0.32.0",
    "torch>=2.6.0",
    "transformers>=4.43.0",
]
